PLAYER=group7
MAP=mapgroup3
L=30
W=40
S=0.01
GUI=false

run:
	java watermelon.sim.watermelon $(MAP) $(L) $(W) $(GUI) $(PLAYER) $(S)

dumb:
	java watermelon.sim.watermelon $(MAP) $(L) $(W) $(GUI) dumb $(S)

compile:
	javac ./watermelon/sim/*.java
